### ISSUE TITLE
Links on website are broken 

### ISSUE THREAD

**Issue by Randl** [mlcommons/training_results_v3.0#2]
On the website, some links are broken. In particular, for NVIDIA+CoreWeave links are of form 
https://github.com/mlcommons/training_results_v3.0/blob/main/NVIDIA%2BCoreWeave/systems/coreweave_hgxh100_n448_ngc23.04_pytorch.json
instead of 
https://github.com/mlcommons/training_results_v3.0/blob/main/NVIDIA_CoreWeave/systems/coreweave_hgxh100_n448_ngc23.04_pytorch.json

**Comment by nathanw-mlc** [comment]
@Randl Thanks for catching this issue. We've fixed the links. Please let us know if you encounter any further problems.
